### ISSUE TITLE
If no browser is available, knitj fails even with --no-browser

### ISSUE THREAD

**Issue by JohnCHarrington** [jhrmnn/knitj#7]
I am running knitj on a remote machine, planning to connect to the knitj server in my local browser. I run `knitj -s -n file.md` and get the following:

```
Traceback (most recent call last):
  File "/home/jh/.local/bin/knitj", line 11, in <module>
    sys.exit(main())
  File "/home/jh/.local/lib/python3.7/site-packages/knitj/cli.py", line 57, in main
    args = parse_cli()
  File "/home/jh/.local/lib/python3.7/site-packages/knitj/cli.py", line 40, in parse_cli
    default=webbrowser.get(),
  File "/home/jh/anaconda3/lib/python3.7/webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```

It appears that the cli.py file is calling `webbrowser.get()` regardless of the `--no-browser` arg.

**Comment by jhrmnn** [comment]
Thanks! Fixed in 0.3.1.
